-- Supabase PostgreSQL Schema for Zauba Scraper Ingestion

CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cin TEXT UNIQUE NOT NULL,
    company_name TEXT NOT NULL,
    status TEXT,
    roc TEXT,
    company_type TEXT,
    incorporation_date DATE,
    email TEXT,
    website TEXT,
    address TEXT,
    state TEXT,
    city TEXT,
    authorized_capital TEXT,
    paid_up_capital TEXT,
    company_category TEXT,
    company_subcategory TEXT,
    source_url TEXT,
    content_hash TEXT,
    scraped_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Index for fast lookup by CIN and Company Name
CREATE INDEX IF NOT EXISTS idx_companies_cin ON public.companies (cin);
CREATE INDEX IF NOT EXISTS idx_companies_name ON public.companies (company_name);

-- Index for reading companies newest-first (latest registered to oldest).
-- Query the data with:  SELECT * FROM companies ORDER BY incorporation_date DESC NULLS LAST;
CREATE INDEX IF NOT EXISTS idx_companies_incorporation_date
    ON public.companies (incorporation_date DESC);

-- Trigger to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_companies_updated_at ON public.companies;

CREATE TRIGGER update_companies_updated_at
    BEFORE UPDATE ON public.companies
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
